In [2]:
import pandas as pd
import os

In [4]:
df1 = pd.read_csv('example.csv')

In [5]:
df1

,공급일자,요일,공급월,공급주차,회원번호,조합원상태,물품대분류,물품중분류,물품소분류,물품명,구매수량,주소-구,주소-동,성별,연령,연령대,구매금액,구매매장,반품_원거래일자,구매시각
0,2018-01-02,화,1,1,272369856,정상회원,과실,과일,사과,사과/유(1.5kg),1.0,수지구,풍덕천동,여,45.0,40대,22207,매장C,NaN,10:04
1,2018-01-02,화,1,1,1506656256,정상회원,채소,버섯,느타리버섯,느타리버섯(300g),1.0,수지구,풍덕천동,여,36.0,30대이하,4977,매장C,NaN,10:05
2,2018-01-02,화,1,1,1506656256,정상회원,축산물,알,유정란,유정란/매장용(10알/국내산),1.0,수지구,풍덕천동,여,36.0,30대이하,7083,매장C,NaN,10:05
3,2018-01-02,화,1,1,1023108864,정상회원,반찬,두부/유부,두부,연두부(100g),1.0,수지구,풍덕천동,여,36.0,30대이하,766,매장C,NaN,10:08
4,2018-01-02,화,1,1,1476143616,정상회원,간식,빵,"식빵, 식사대용",아침빵(240g/8개)/매장,1.0,수지구,풍덕천동,여,34.0,30대이하,4403,매장C,NaN,10:09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
705566,2018-06-30,토,6,26,146297344,정상회원,수산,건어물,멸치류,국물멸치(300g),1.0,수지구,성복동,여,51.0,50대,9189,매장A,NaN,17:56
705567,2018-06-30,토,6,26,1532985472,정상회원,수산,해조,미역/다시마,자른다시마(100g),1.0,수지구,동천동,여,63.0,60대,5169,매장A,NaN,14:37
705568,2018-06-30,토,6,26,1532985472,정상회원,반찬,두부/유부,두부,두부(1모:420g),2.0,수지구,동천동,여,63.0,60대,7466,매장A,NaN,14:37
705569,2018-06-30,토,6,26,1209779776,정상회원,간식,과자,스낵,하늘바다새우(60g),1.0,수지구,동천동,여,41.0,40대,3542,매장A,NaN,18:04
705570,2018-06-30,토,6,26,301961920,정상회원,음료,음료,빙과,포도꽁꽁(120ml)/매장용,1.0,수지구,풍덕천동,여,49.0,40대,1914,매장A,NaN,16:36

In [6]:
df1.shape

(705571, 20)

In [7]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 705571 entries, 0 to 705570
Data columns (total 20 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   공급일자      705571 non-null  object
 1   요일        705571 non-null  object
 2   공급월       705571 non-null  int64
 3   공급주차      705571 non-null  int64
 4   회원번호      705571 non-null  int64
 5   조합원상태     705571 non-null  object
 6   물품대분류     705571 non-null  object
 7   물품중분류     705571 non-null  object
 8   물품소분류     705571 non-null  object
 9   물품명       705571 non-null  object
 10  구매수량      705571 non-null  float64
 11  주소-구      705571 non-null  object
 12  주소-동      705571 non-null  object
 13  성별        705566 non-null  object
 14  연령        705538 non-null  float64
 15  연령대       705538 non-null  object
 16  구매금액      705571 non-null  int64
 17  구매매장      705571 non-null  object
 18  반품_원거래일자  11234 non-null   float64
 19  구매시각      705571 non-null  object
dtypes: float64(3), int64(4), object(13)
memory usage: 107.7+ MB

In [9]:
df1.describe()

,공급월,공급주차,회원번호,구매수량,연령,구매금액,반품_원거래일자
count,705571.000000,705571.000000,7.055710e+05,705571.000000,705538.000000,7.055710e+05,1.123400e+04
mean,3.510817,13.500022,7.390639e+08,1.138203,50.756234,1.092004e+04,2.018034e+07
std,1.719153,7.517818,4.251288e+08,0.754448,11.418854,1.670323e+04,5.229237e+02
min,1.000000,1.000000,1.876416e+07,-50.000000,1.000000,-6.662160e+05,2.017121e+07
25%,2.000000,7.000000,3.906917e+08,1.000000,42.000000,4.116000e+03,2.018021e+07
50%,4.000000,13.000000,7.456573e+08,1.000000,49.000000,7.275000e+03,2.018040e+07
75%,5.000000,20.000000,1.045186e+09,1.000000,58.000000,1.263500e+04,2.018052e+07
max,6.000000,26.000000,1.670621e+09,50.000000,108.000000,2.751014e+06,2.018063e+07

In [11]:
df1.head() ## 상위 5개

,공급일자,요일,공급월,공급주차,회원번호,조합원상태,물품대분류,물품중분류,물품소분류,물품명,구매수량,주소-구,주소-동,성별,연령,연령대,구매금액,구매매장,반품_원거래일자,구매시각
0,2018-01-02,화,1,1,272369856,정상회원,과실,과일,사과,사과/유(1.5kg),1.0,수지구,풍덕천동,여,45.0,40대,22207,매장C,NaN,10:04
1,2018-01-02,화,1,1,1506656256,정상회원,채소,버섯,느타리버섯,느타리버섯(300g),1.0,수지구,풍덕천동,여,36.0,30대이하,4977,매장C,NaN,10:05
2,2018-01-02,화,1,1,1506656256,정상회원,축산물,알,유정란,유정란/매장용(10알/국내산),1.0,수지구,풍덕천동,여,36.0,30대이하,7083,매장C,NaN,10:05
3,2018-01-02,화,1,1,1023108864,정상회원,반찬,두부/유부,두부,연두부(100g),1.0,수지구,풍덕천동,여,36.0,30대이하,766,매장C,NaN,10:08
4,2018-01-02,화,1,1,1476143616,정상회원,간식,빵,"식빵, 식사대용",아침빵(240g/8개)/매장,1.0,수지구,풍덕천동,여,34.0,30대이하,4403,매장C,NaN,10:09

In [12]:
df1.tail() ## 아래서부터 5개

,공급일자,요일,공급월,공급주차,회원번호,조합원상태,물품대분류,물품중분류,물품소분류,물품명,구매수량,주소-구,주소-동,성별,연령,연령대,구매금액,구매매장,반품_원거래일자,구매시각
705566,2018-06-30,토,6,26,146297344,정상회원,수산,건어물,멸치류,국물멸치(300g),1.0,수지구,성복동,여,51.0,50대,9189,매장A,NaN,17:56
705567,2018-06-30,토,6,26,1532985472,정상회원,수산,해조,미역/다시마,자른다시마(100g),1.0,수지구,동천동,여,63.0,60대,5169,매장A,NaN,14:37
705568,2018-06-30,토,6,26,1532985472,정상회원,반찬,두부/유부,두부,두부(1모:420g),2.0,수지구,동천동,여,63.0,60대,7466,매장A,NaN,14:37
705569,2018-06-30,토,6,26,1209779776,정상회원,간식,과자,스낵,하늘바다새우(60g),1.0,수지구,동천동,여,41.0,40대,3542,매장A,NaN,18:04
705570,2018-06-30,토,6,26,301961920,정상회원,음료,음료,빙과,포도꽁꽁(120ml)/매장용,1.0,수지구,풍덕천동,여,49.0,40대,1914,매장A,NaN,16:36

In [15]:
df1.isnull()

,공급일자,요일,공급월,공급주차,회원번호,조합원상태,물품대분류,물품중분류,물품소분류,물품명,구매수량,주소-구,주소-동,성별,연령,연령대,구매금액,구매매장,반품_원거래일자,구매시각
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
705566,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
705567,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
705568,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
705569,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
705570,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False

In [16]:
df1.isnull().sum()

공급일자             0
요일               0
공급월              0
공급주차             0
회원번호             0
조합원상태            0
물품대분류            0
물품중분류            0
물품소분류            0
물품명              0
구매수량             0
주소-구             0
주소-동             0
성별               5
연령              33
연령대             33
구매금액             0
구매매장             0
반품_원거래일자    694337
구매시각             0
dtype: int64

In [17]:
df1.columns

Index(['공급일자', '요일', '공급월', '공급주차', '회원번호', '조합원상태', '물품대분류', '물품중분류', '물품소분류',
       '물품명', '구매수량', '주소-구', '주소-동', '성별', '연령', '연령대', '구매금액', '구매매장',
       '반품_원거래일자', '구매시각'],
      dtype='object')

In [18]:
## 데이터 추출

In [19]:
df1['구매금액']

0         22207
1          4977
2          7083
3           766
4          4403
          ...
705566     9189
705567     5169
705568     7466
705569     3542
705570     1914
Name: 구매금액, Length: 705571, dtype: int64

In [20]:
df1['구매금액'].sum()

7704862190

In [21]:
df1['구매금액'].mean()

10920.038082630947

In [22]:
df1['구매금액'].describe()

count    7.055710e+05
mean     1.092004e+04
std      1.670323e+04
min     -6.662160e+05
25%      4.116000e+03
50%      7.275000e+03
75%      1.263500e+04
max      2.751014e+06
Name: 구매금액, dtype: float64

In [24]:
df1[['구매금액','성별']] ## 데이터 프레임 형태로 불러올 시 대괄호

         구매금액 성별
0       22207  여
1        4977  여
2        7083  여
3         766  여
4        4403  여
...       ... ..
705566   9189  여
705567   5169  여
705568   7466  여
705569   3542  여
705570   1914  여

[705571 rows x 2 columns]

In [27]:
df2 = df1[['구매금액','성별']] ## 데이터 프레임 형태로 불러올 시 대괄호 2개

In [28]:
df2

         구매금액 성별
0       22207  여
1        4977  여
2        7083  여
3         766  여
4        4403  여
...       ... ..
705566   9189  여
705567   5169  여
705568   7466  여
705569   3542  여
705570   1914  여

[705571 rows x 2 columns]

In [29]:
df1[['구매금액', '물품대분류', '물품중분류']]

         구매금액 물품대분류  물품중분류
0       22207    과실     과일
1        4977    채소     버섯
2        7083   축산물      알
3         766    반찬  두부/유부
4        4403    간식      빵
...       ...   ...    ...
705566   9189    수산    건어물
705567   5169    수산     해조
705568   7466    반찬  두부/유부
705569   3542    간식     과자
705570   1914    음료     음료

[705571 rows x 3 columns]

In [31]:
df1.iloc[1]

공급일자          2018-01-02
요일                     화
공급월                    1
공급주차                   1
회원번호          1177875136
조합원상태               정상회원
물품대분류                 채소
물품중분류               뿌리채소
물품소분류                 연근
물품명         통연근/세척(400g)
구매수량                 1.0
주소-구                 수지구
주소-동                풍덕천동
성별                     여
연령                  34.0
연령대                30대이하
구매금액                7179
구매매장                 매장C
반품_원거래일자             NaN
구매시각               10:19
Name: 10, dtype: object

In [32]:
df1.iloc[-1]

공급일자             2018-06-30
요일                        토
공급월                       6
공급주차                     26
회원번호              301961920
조합원상태                  정상회원
물품대분류                    음료
물품중분류                    음료
물품소분류                    빙과
물품명         포도꽁꽁(120ml)/매장용
구매수량                    1.0
주소-구                    수지구
주소-동                   풍덕천동
성별                        여
연령                     49.0
연령대                     40대
구매금액                   1914
구매매장                    매장A
반품_원거래일자                NaN
구매시각                  16:36
Name: 705570, dtype: object

In [33]:
df1.iloc[0:11]

,공급일자,요일,공급월,공급주차,회원번호,조합원상태,물품대분류,물품중분류,물품소분류,물품명,구매수량,주소-구,주소-동,성별,연령,연령대,구매금액,구매매장,반품_원거래일자,구매시각
0,2018-01-02,화,1,1,272369856,정상회원,과실,과일,사과,사과/유(1.5kg),1.0,수지구,풍덕천동,여,45.0,40대,22207,매장C,NaN,10:04
1,2018-01-02,화,1,1,1506656256,정상회원,채소,버섯,느타리버섯,느타리버섯(300g),1.0,수지구,풍덕천동,여,36.0,30대이하,4977,매장C,NaN,10:05
2,2018-01-02,화,1,1,1506656256,정상회원,축산물,알,유정란,유정란/매장용(10알/국내산),1.0,수지구,풍덕천동,여,36.0,30대이하,7083,매장C,NaN,10:05
3,2018-01-02,화,1,1,1023108864,정상회원,반찬,두부/유부,두부,연두부(100g),1.0,수지구,풍덕천동,여,36.0,30대이하,766,매장C,NaN,10:08
4,2018-01-02,화,1,1,1476143616,정상회원,간식,빵,"식빵, 식사대용",아침빵(240g/8개)/매장,1.0,수지구,풍덕천동,여,34.0,30대이하,4403,매장C,NaN,10:09
5,2018-01-02,화,1,1,716128320,정상회원,축산물,알,유정란,유정란/매장용(10알/국내산),1.0,수지구,풍덕천동,여,51.0,50대,7083,매장C,NaN,10:10
6,2018-01-02,화,1,1,743192512,정상회원,채소,과일채소,딸기,딸기/(500g),1.0,수지구,성복동,여,51.0,50대,17038,매장C,NaN,10:12
7,2018-01-02,화,1,1,743192512,정상회원,채소,잎/줄기채소,어린잎채소,어린잎채소(100g),2.0,수지구,성복동,여,51.0,50대,11104,매장C,NaN,10:12
8,2018-01-02,화,1,1,743192512,정상회원,채소,양념채소,생강,생강(300g),1.0,수지구,성복동,여,51.0,50대,7083,매장C,NaN,10:12
9,2018-01-02,화,1,1,743192512,정상회원,채소,쌈채소류,쌈케일,쌈케일(150g),1.0,수지구,성복동,여,51.0,50대,2584,매장C,NaN,10:12
10,2018-01-02,화,1,1,1177875136,정상회원,채소,뿌리채소,연근,통연근/세척(400g),1.0,수지구,풍덕천동,여,34.0,30대이하,7179,매장C,NaN,10:19

In [34]:
df1.iloc[100:]

,공급일자,요일,공급월,공급주차,회원번호,조합원상태,물품대분류,물품중분류,물품소분류,물품명,구매수량,주소-구,주소-동,성별,연령,연령대,구매금액,구매매장,반품_원거래일자,구매시각
100,2018-01-02,화,1,1,673577664,정상회원,반찬,밑반찬,김가공,구운도시락김(5g*3봉),1.0,수지구,풍덕천동,여,36.0,30대이하,2872,매장C,NaN,13:42
101,2018-01-02,화,1,1,362835008,정상회원,반찬,두부/유부,두부,두부(1모:420g),1.0,수지구,풍덕천동,여,50.0,50대,3829,매장C,NaN,13:46
102,2018-01-02,화,1,1,202536000,정상회원,반찬,밑반찬,볶음,고추장멸치볶음(150g),1.0,수지구,풍덕천동,여,49.0,40대,12444,매장C,NaN,13:50
103,2018-01-02,화,1,1,748248256,정상회원,채소,버섯,느타리버섯,느타리버섯(300g),1.0,기흥구,중동,여,41.0,40대,4977,매장C,NaN,13:53
104,2018-01-02,화,1,1,1132982208,정상회원,음료,음료,과즙,사과당근즙(150ml),1.0,수지구,풍덕천동,여,42.0,40대,1914,매장C,NaN,13:58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
705566,2018-06-30,토,6,26,146297344,정상회원,수산,건어물,멸치류,국물멸치(300g),1.0,수지구,성복동,여,51.0,50대,9189,매장A,NaN,17:56
705567,2018-06-30,토,6,26,1532985472,정상회원,수산,해조,미역/다시마,자른다시마(100g),1.0,수지구,동천동,여,63.0,60대,5169,매장A,NaN,14:37
705568,2018-06-30,토,6,26,1532985472,정상회원,반찬,두부/유부,두부,두부(1모:420g),2.0,수지구,동천동,여,63.0,60대,7466,매장A,NaN,14:37
705569,2018-06-30,토,6,26,1209779776,정상회원,간식,과자,스낵,하늘바다새우(60g),1.0,수지구,동천동,여,41.0,40대,3542,매장A,NaN,18:04
705570,2018-06-30,토,6,26,301961920,정상회원,음료,음료,빙과,포도꽁꽁(120ml)/매장용,1.0,수지구,풍덕천동,여,49.0,40대,1914,매장A,NaN,16:36

In [35]:
df2 = df1.iloc[100:]

In [36]:
df2.shape

(705471, 20)

In [37]:
## 데이터 정렬

In [38]:
df1

,공급일자,요일,공급월,공급주차,회원번호,조합원상태,물품대분류,물품중분류,물품소분류,물품명,구매수량,주소-구,주소-동,성별,연령,연령대,구매금액,구매매장,반품_원거래일자,구매시각
0,2018-01-02,화,1,1,272369856,정상회원,과실,과일,사과,사과/유(1.5kg),1.0,수지구,풍덕천동,여,45.0,40대,22207,매장C,NaN,10:04
1,2018-01-02,화,1,1,1506656256,정상회원,채소,버섯,느타리버섯,느타리버섯(300g),1.0,수지구,풍덕천동,여,36.0,30대이하,4977,매장C,NaN,10:05
2,2018-01-02,화,1,1,1506656256,정상회원,축산물,알,유정란,유정란/매장용(10알/국내산),1.0,수지구,풍덕천동,여,36.0,30대이하,7083,매장C,NaN,10:05
3,2018-01-02,화,1,1,1023108864,정상회원,반찬,두부/유부,두부,연두부(100g),1.0,수지구,풍덕천동,여,36.0,30대이하,766,매장C,NaN,10:08
4,2018-01-02,화,1,1,1476143616,정상회원,간식,빵,"식빵, 식사대용",아침빵(240g/8개)/매장,1.0,수지구,풍덕천동,여,34.0,30대이하,4403,매장C,NaN,10:09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
705566,2018-06-30,토,6,26,146297344,정상회원,수산,건어물,멸치류,국물멸치(300g),1.0,수지구,성복동,여,51.0,50대,9189,매장A,NaN,17:56
705567,2018-06-30,토,6,26,1532985472,정상회원,수산,해조,미역/다시마,자른다시마(100g),1.0,수지구,동천동,여,63.0,60대,5169,매장A,NaN,14:37
705568,2018-06-30,토,6,26,1532985472,정상회원,반찬,두부/유부,두부,두부(1모:420g),2.0,수지구,동천동,여,63.0,60대,7466,매장A,NaN,14:37
705569,2018-06-30,토,6,26,1209779776,정상회원,간식,과자,스낵,하늘바다새우(60g),1.0,수지구,동천동,여,41.0,40대,3542,매장A,NaN,18:04
705570,2018-06-30,토,6,26,301961920,정상회원,음료,음료,빙과,포도꽁꽁(120ml)/매장용,1.0,수지구,풍덕천동,여,49.0,40대,1914,매장A,NaN,16:36

In [39]:
df1.sort_values(by='구매금액') ## 구매금액의 오름차순 정렬

,공급일자,요일,공급월,공급주차,회원번호,조합원상태,물품대분류,물품중분류,물품소분류,물품명,구매수량,주소-구,주소-동,성별,연령,연령대,구매금액,구매매장,반품_원거래일자,구매시각
157876,2018-02-09,금,2,6,1529962048,정상회원,건강,건강일반,추출/농축액,흑염소진액(100ml*30봉),-4.0,수지구,풍덕천동,남,29.0,30대이하,-666216,매장C,20180206.0,16:59
181579,2018-02-14,수,2,7,747242304,정상회원,건강,건강일반,추출/농축액,흑염소진액(100ml*30봉),-4.0,수지구,신봉동,여,54.0,50대,-666216,매장C,20180206.0,14:06
144210,2018-02-06,화,2,6,747242304,정상회원,건강,건강일반,추출/농축액,흑염소진액(100ml*30봉),-3.0,수지구,신봉동,여,54.0,50대,-499662,매장C,20180206.0,16:42
142077,2018-02-06,화,2,6,307284928,정상회원,건강,건강일반,추출/농축액,흑염소진액(100ml*30봉),-3.0,수지구,풍덕천동,여,53.0,50대,-499662,매장C,20180206.0,18:52
145272,2018-02-06,화,2,6,1031186176,정상회원,건강,건강일반,추출/농축액,흑염소진액(100ml*30봉),-3.0,수지구,풍덕천동,여,51.0,50대,-499662,매장C,20180206.0,16:04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
585654,2018-06-01,금,6,22,153723200,정상회원,채소,버섯,상황버섯,린테우스상황버섯(200g/유),5.0,수지구,동천동,여,52.0,50대,1445383,매장A,NaN,18:13
155255,2018-02-09,금,2,6,236805184,정상회원,건강,건강일반,건강/기타,홍삼/도라지절편모음(각 20g*5개),17.0,수지구,상현동,여,39.0,30대이하,1448255,매장B,NaN,12:17
127674,2018-02-02,금,2,5,938963392,정상회원,간식,과자,한과/유과,한과모음3(1.2kg),20.0,수지구,상현동,여,40.0,40대,1588964,매장B,NaN,16:22
208148,2018-02-23,금,2,8,742461248,정상회원,양념/가루,장,메주,메주(1말:약6-7kg:솔뫼),9.0,분당구,정자동,남,106.0,70대이상,1688514,매장D,NaN,11:30
182163,2018-02-14,수,2,7,854303808,정상회원,채소,뿌리채소,산양삼,산양삼/7년근이상(5주),6.0,수지구,풍덕천동,여,52.0,50대,2751014,매장B,NaN,12:36

In [41]:
df1.sort_values(by='구매금액', ascending=False) ## 구매금액의 내림차순 정렬

,공급일자,요일,공급월,공급주차,회원번호,조합원상태,물품대분류,물품중분류,물품소분류,물품명,구매수량,주소-구,주소-동,성별,연령,연령대,구매금액,구매매장,반품_원거래일자,구매시각
182163,2018-02-14,수,2,7,854303808,정상회원,채소,뿌리채소,산양삼,산양삼/7년근이상(5주),6.0,수지구,풍덕천동,여,52.0,50대,2751014,매장B,NaN,12:36
208148,2018-02-23,금,2,8,742461248,정상회원,양념/가루,장,메주,메주(1말:약6-7kg:솔뫼),9.0,분당구,정자동,남,106.0,70대이상,1688514,매장D,NaN,11:30
127674,2018-02-02,금,2,5,938963392,정상회원,간식,과자,한과/유과,한과모음3(1.2kg),20.0,수지구,상현동,여,40.0,40대,1588964,매장B,NaN,16:22
155255,2018-02-09,금,2,6,236805184,정상회원,건강,건강일반,건강/기타,홍삼/도라지절편모음(각 20g*5개),17.0,수지구,상현동,여,39.0,30대이하,1448255,매장B,NaN,12:17
585654,2018-06-01,금,6,22,153723200,정상회원,채소,버섯,상황버섯,린테우스상황버섯(200g/유),5.0,수지구,동천동,여,52.0,50대,1445383,매장A,NaN,18:13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144210,2018-02-06,화,2,6,747242304,정상회원,건강,건강일반,추출/농축액,흑염소진액(100ml*30봉),-3.0,수지구,신봉동,여,54.0,50대,-499662,매장C,20180206.0,16:42
145272,2018-02-06,화,2,6,1031186176,정상회원,건강,건강일반,추출/농축액,흑염소진액(100ml*30봉),-3.0,수지구,풍덕천동,여,51.0,50대,-499662,매장C,20180206.0,16:04
142077,2018-02-06,화,2,6,307284928,정상회원,건강,건강일반,추출/농축액,흑염소진액(100ml*30봉),-3.0,수지구,풍덕천동,여,53.0,50대,-499662,매장C,20180206.0,18:52
181579,2018-02-14,수,2,7,747242304,정상회원,건강,건강일반,추출/농축액,흑염소진액(100ml*30봉),-4.0,수지구,신봉동,여,54.0,50대,-666216,매장C,20180206.0,14:06
157876,2018-02-09,금,2,6,1529962048,정상회원,건강,건강일반,추출/농축액,흑염소진액(100ml*30봉),-4.0,수지구,풍덕천동,남,29.0,30대이하,-666216,매장C,20180206.0,16:59

In [43]:
df1.sort_values(by='구매수량',ascending=False)

,공급일자,요일,공급월,공급주차,회원번호,조합원상태,물품대분류,물품중분류,물품소분류,물품명,구매수량,주소-구,주소-동,성별,연령,연령대,구매금액,구매매장,반품_원거래일자,구매시각
665064,2018-06-21,목,6,25,86983296,정상회원,채소,콩나물,숙주나물,숙주나물(300g),50.0,수지구,풍덕천동,여,51.0,50대,201014,매장A,NaN,17:22
665636,2018-06-21,목,6,25,86983296,정상회원,채소,버섯,팽이버섯,팽이버섯(150g),50.0,수지구,풍덕천동,여,51.0,50대,57432,매장A,NaN,17:22
664021,2018-06-21,목,6,25,86983296,정상회원,채소,잎/줄기채소,깻잎,깻잎(30장),50.0,수지구,풍덕천동,여,51.0,50대,90935,매장A,NaN,17:22
382065,2018-04-09,월,4,15,1230917760,정상회원,수산,소금,가공소금,볶은왕소금(500g),50.0,기타,기타,남,43.0,40대,162725,매장C,NaN,17:45
665065,2018-06-21,목,6,25,86983296,정상회원,채소,열매채소,풋고추,풋고추(150g),50.0,수지구,풍덕천동,여,51.0,50대,114865,매장A,NaN,17:22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
612002,2018-06-07,목,6,23,548171456,정상회원,축산물,유제품,요구르트,블루베리요구르트(120ml),-43.0,수지구,풍덕천동,여,52.0,50대,-98784,매장C,20180606.0,19:38
663461,2018-06-21,목,6,25,86983296,정상회원,채소,버섯,팽이버섯,팽이버섯(150g),-50.0,수지구,풍덕천동,여,51.0,50대,-57432,매장A,20180621.0,17:22
665066,2018-06-21,목,6,25,86983296,정상회원,채소,콩나물,숙주나물,숙주나물(300g),-50.0,수지구,풍덕천동,여,51.0,50대,-201014,매장A,20180621.0,17:22
664534,2018-06-21,목,6,25,86983296,정상회원,채소,잎/줄기채소,깻잎,깻잎(30장),-50.0,수지구,풍덕천동,여,51.0,50대,-90935,매장A,20180621.0,17:22
663462,2018-06-21,목,6,25,86983296,정상회원,채소,열매채소,풋고추,풋고추(150g),-50.0,수지구,풍덕천동,여,51.0,50대,-114865,매장A,20180621.0,17:22

In [45]:
df1.sort_values(by=['구매수량', '연령']) ## 구매수량 오름차순 후 연령 오름차순으로 정렬

,공급일자,요일,공급월,공급주차,회원번호,조합원상태,물품대분류,물품중분류,물품소분류,물품명,구매수량,주소-구,주소-동,성별,연령,연령대,구매금액,구매매장,반품_원거래일자,구매시각
663461,2018-06-21,목,6,25,86983296,정상회원,채소,버섯,팽이버섯,팽이버섯(150g),-50.0,수지구,풍덕천동,여,51.0,50대,-57432,매장A,20180621.0,17:22
663462,2018-06-21,목,6,25,86983296,정상회원,채소,열매채소,풋고추,풋고추(150g),-50.0,수지구,풍덕천동,여,51.0,50대,-114865,매장A,20180621.0,17:22
664534,2018-06-21,목,6,25,86983296,정상회원,채소,잎/줄기채소,깻잎,깻잎(30장),-50.0,수지구,풍덕천동,여,51.0,50대,-90935,매장A,20180621.0,17:22
665066,2018-06-21,목,6,25,86983296,정상회원,채소,콩나물,숙주나물,숙주나물(300g),-50.0,수지구,풍덕천동,여,51.0,50대,-201014,매장A,20180621.0,17:22
612002,2018-06-07,목,6,23,548171456,정상회원,축산물,유제품,요구르트,블루베리요구르트(120ml),-43.0,수지구,풍덕천동,여,52.0,50대,-98784,매장C,20180606.0,19:38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
386251,2018-04-09,월,4,15,1230917760,정상회원,반찬,절임/장아찌,절임,무쌈(300g),50.0,기타,기타,남,43.0,40대,191441,매장C,NaN,17:45
664021,2018-06-21,목,6,25,86983296,정상회원,채소,잎/줄기채소,깻잎,깻잎(30장),50.0,수지구,풍덕천동,여,51.0,50대,90935,매장A,NaN,17:22
665064,2018-06-21,목,6,25,86983296,정상회원,채소,콩나물,숙주나물,숙주나물(300g),50.0,수지구,풍덕천동,여,51.0,50대,201014,매장A,NaN,17:22
665065,2018-06-21,목,6,25,86983296,정상회원,채소,열매채소,풋고추,풋고추(150g),50.0,수지구,풍덕천동,여,51.0,50대,114865,매장A,NaN,17:22
665636,2018-06-21,목,6,25,86983296,정상회원,채소,버섯,팽이버섯,팽이버섯(150g),50.0,수지구,풍덕천동,여,51.0,50대,57432,매장A,NaN,17:22

In [46]:
df1.sort_values(by=['구매수량', '연령'],ascending=False) ## 구매수량 내림차순 후 연령 내림차순으로 정렬

,공급일자,요일,공급월,공급주차,회원번호,조합원상태,물품대분류,물품중분류,물품소분류,물품명,구매수량,주소-구,주소-동,성별,연령,연령대,구매금액,구매매장,반품_원거래일자,구매시각
664021,2018-06-21,목,6,25,86983296,정상회원,채소,잎/줄기채소,깻잎,깻잎(30장),50.0,수지구,풍덕천동,여,51.0,50대,90935,매장A,NaN,17:22
665064,2018-06-21,목,6,25,86983296,정상회원,채소,콩나물,숙주나물,숙주나물(300g),50.0,수지구,풍덕천동,여,51.0,50대,201014,매장A,NaN,17:22
665065,2018-06-21,목,6,25,86983296,정상회원,채소,열매채소,풋고추,풋고추(150g),50.0,수지구,풍덕천동,여,51.0,50대,114865,매장A,NaN,17:22
665636,2018-06-21,목,6,25,86983296,정상회원,채소,버섯,팽이버섯,팽이버섯(150g),50.0,수지구,풍덕천동,여,51.0,50대,57432,매장A,NaN,17:22
382065,2018-04-09,월,4,15,1230917760,정상회원,수산,소금,가공소금,볶은왕소금(500g),50.0,기타,기타,남,43.0,40대,162725,매장C,NaN,17:45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
612002,2018-06-07,목,6,23,548171456,정상회원,축산물,유제품,요구르트,블루베리요구르트(120ml),-43.0,수지구,풍덕천동,여,52.0,50대,-98784,매장C,20180606.0,19:38
663461,2018-06-21,목,6,25,86983296,정상회원,채소,버섯,팽이버섯,팽이버섯(150g),-50.0,수지구,풍덕천동,여,51.0,50대,-57432,매장A,20180621.0,17:22
663462,2018-06-21,목,6,25,86983296,정상회원,채소,열매채소,풋고추,풋고추(150g),-50.0,수지구,풍덕천동,여,51.0,50대,-114865,매장A,20180621.0,17:22
664534,2018-06-21,목,6,25,86983296,정상회원,채소,잎/줄기채소,깻잎,깻잎(30장),-50.0,수지구,풍덕천동,여,51.0,50대,-90935,매장A,20180621.0,17:22
665066,2018-06-21,목,6,25,86983296,정상회원,채소,콩나물,숙주나물,숙주나물(300g),-50.0,수지구,풍덕천동,여,51.0,50대,-201014,매장A,20180621.0,17:22

In [47]:
df1.sort_values(by=['구매수량', '연령'],ascending=[False,True]) ## 구매수량 내림차순 후 연령 오름차순으로 정렬

,공급일자,요일,공급월,공급주차,회원번호,조합원상태,물품대분류,물품중분류,물품소분류,물품명,구매수량,주소-구,주소-동,성별,연령,연령대,구매금액,구매매장,반품_원거래일자,구매시각
382065,2018-04-09,월,4,15,1230917760,정상회원,수산,소금,가공소금,볶은왕소금(500g),50.0,기타,기타,남,43.0,40대,162725,매장C,NaN,17:45
386251,2018-04-09,월,4,15,1230917760,정상회원,반찬,절임/장아찌,절임,무쌈(300g),50.0,기타,기타,남,43.0,40대,191441,매장C,NaN,17:45
664021,2018-06-21,목,6,25,86983296,정상회원,채소,잎/줄기채소,깻잎,깻잎(30장),50.0,수지구,풍덕천동,여,51.0,50대,90935,매장A,NaN,17:22
665064,2018-06-21,목,6,25,86983296,정상회원,채소,콩나물,숙주나물,숙주나물(300g),50.0,수지구,풍덕천동,여,51.0,50대,201014,매장A,NaN,17:22
665065,2018-06-21,목,6,25,86983296,정상회원,채소,열매채소,풋고추,풋고추(150g),50.0,수지구,풍덕천동,여,51.0,50대,114865,매장A,NaN,17:22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
612002,2018-06-07,목,6,23,548171456,정상회원,축산물,유제품,요구르트,블루베리요구르트(120ml),-43.0,수지구,풍덕천동,여,52.0,50대,-98784,매장C,20180606.0,19:38
663461,2018-06-21,목,6,25,86983296,정상회원,채소,버섯,팽이버섯,팽이버섯(150g),-50.0,수지구,풍덕천동,여,51.0,50대,-57432,매장A,20180621.0,17:22
663462,2018-06-21,목,6,25,86983296,정상회원,채소,열매채소,풋고추,풋고추(150g),-50.0,수지구,풍덕천동,여,51.0,50대,-114865,매장A,20180621.0,17:22
664534,2018-06-21,목,6,25,86983296,정상회원,채소,잎/줄기채소,깻잎,깻잎(30장),-50.0,수지구,풍덕천동,여,51.0,50대,-90935,매장A,20180621.0,17:22
665066,2018-06-21,목,6,25,86983296,정상회원,채소,콩나물,숙주나물,숙주나물(300g),-50.0,수지구,풍덕천동,여,51.0,50대,-201014,매장A,20180621.0,17:22

In [49]:
df1.sort_values(by=['구매수량', '연령'],ascending=[False,True]).iloc[:10] ## 구매수량 내림차순 후 연령 오름차순으로 정렬 10개

,공급일자,요일,공급월,공급주차,회원번호,조합원상태,물품대분류,물품중분류,물품소분류,물품명,구매수량,주소-구,주소-동,성별,연령,연령대,구매금액,구매매장,반품_원거래일자,구매시각
382065,2018-04-09,월,4,15,1230917760,정상회원,수산,소금,가공소금,볶은왕소금(500g),50.0,기타,기타,남,43.0,40대,162725,매장C,NaN,17:45
386251,2018-04-09,월,4,15,1230917760,정상회원,반찬,절임/장아찌,절임,무쌈(300g),50.0,기타,기타,남,43.0,40대,191441,매장C,NaN,17:45
664021,2018-06-21,목,6,25,86983296,정상회원,채소,잎/줄기채소,깻잎,깻잎(30장),50.0,수지구,풍덕천동,여,51.0,50대,90935,매장A,NaN,17:22
665064,2018-06-21,목,6,25,86983296,정상회원,채소,콩나물,숙주나물,숙주나물(300g),50.0,수지구,풍덕천동,여,51.0,50대,201014,매장A,NaN,17:22
665065,2018-06-21,목,6,25,86983296,정상회원,채소,열매채소,풋고추,풋고추(150g),50.0,수지구,풍덕천동,여,51.0,50대,114865,매장A,NaN,17:22
665636,2018-06-21,목,6,25,86983296,정상회원,채소,버섯,팽이버섯,팽이버섯(150g),50.0,수지구,풍덕천동,여,51.0,50대,57432,매장A,NaN,17:22
607549,2018-06-06,수,6,23,548171456,정상회원,축산물,유제품,요구르트,블루베리요구르트(120ml),43.0,수지구,풍덕천동,여,52.0,50대,98784,매장C,NaN,10:35
659553,2018-06-20,수,6,25,157158656,정상회원,채소,열매채소,오이,오이(5개),40.0,수지구,신봉동,여,50.0,50대,168468,매장D,NaN,12:23
276072,2018-03-12,월,3,11,595068864,정상회원,양념/가루,가루,양념가루,카레(매운맛: 100g),40.0,수지구,신봉동,여,53.0,50대,206757,매장D,NaN,11:39
277720,2018-03-12,월,3,11,595068864,정상회원,양념/가루,가루,양념가루,카레(순한맛:100g),40.0,수지구,신봉동,여,53.0,50대,206757,매장D,NaN,11:39

In [51]:
### 데이터 필터

In [52]:
df1['연령대'].value_counts()

40대      270573
50대      174458
30대이하    106392
60대       95019
70대이상     59096
Name: 연령대, dtype: int64

In [53]:
df1['연령대'] == '40대'

0          True
1         False
2         False
3         False
4         False
          ...
705566    False
705567    False
705568    False
705569     True
705570     True
Name: 연령대, Length: 705571, dtype: bool

In [56]:
cond1 = (df1['연령대'] == '40대')
df1.loc[cond1] ## 연령대에서 40대의 데이터만 불러옴

,공급일자,요일,공급월,공급주차,회원번호,조합원상태,물품대분류,물품중분류,물품소분류,물품명,구매수량,주소-구,주소-동,성별,연령,연령대,구매금액,구매매장,반품_원거래일자,구매시각
0,2018-01-02,화,1,1,272369856,정상회원,과실,과일,사과,사과/유(1.5kg),1.0,수지구,풍덕천동,여,45.0,40대,22207,매장C,NaN,10:04
17,2018-01-02,화,1,1,1049686784,정상회원,간식,식사대용,식사대용/기타,닭고기볶음밥(300g),1.0,수지구,풍덕천동,여,40.0,40대,5743,매장C,NaN,10:31
18,2018-01-02,화,1,1,164510272,정상회원,채소,양념채소,양파,양파(2kg),1.0,수지구,풍덕천동,여,42.0,40대,8711,매장C,NaN,10:32
19,2018-01-02,화,1,1,1185171072,정상회원,양념/가루,가루,양념가루,카레(순한맛:100g),1.0,수지구,풍덕천동,여,47.0,40대,5169,매장C,NaN,10:37
20,2018-01-02,화,1,1,1206815744,정상회원,채소,양념채소,대파,대파(700g),1.0,수지구,풍덕천동,여,42.0,40대,5265,매장C,NaN,10:39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
705556,2018-06-30,토,6,26,572193664,정상회원,반찬,두부/유부,콩가공/기타,콩국물(300g),1.0,수지구,풍덕천동,여,46.0,40대,2202,매장A,NaN,13:48
705560,2018-06-30,토,6,26,1333795840,정상회원,반찬,밑반찬,김가공,김부각(50g),1.0,수지구,풍덕천동,여,41.0,40대,7275,매장A,NaN,15:28
705561,2018-06-30,토,6,26,1333795840,정상회원,채소,잎/줄기채소,브로컬리,브로컬리(250g),1.0,수지구,풍덕천동,여,41.0,40대,3982,매장A,NaN,15:28
705569,2018-06-30,토,6,26,1209779776,정상회원,간식,과자,스낵,하늘바다새우(60g),1.0,수지구,동천동,여,41.0,40대,3542,매장A,NaN,18:04
705570,2018-06-30,토,6,26,301961920,정상회원,음료,음료,빙과,포도꽁꽁(120ml)/매장용,1.0,수지구,풍덕천동,여,49.0,40대,1914,매장A,NaN,16:36

In [57]:
cond2 = (df1['연령대'] != '40대')
df1.loc[cond2] ## 40대를 제외한 데이터만 불러옴

,공급일자,요일,공급월,공급주차,회원번호,조합원상태,물품대분류,물품중분류,물품소분류,물품명,구매수량,주소-구,주소-동,성별,연령,연령대,구매금액,구매매장,반품_원거래일자,구매시각
1,2018-01-02,화,1,1,1506656256,정상회원,채소,버섯,느타리버섯,느타리버섯(300g),1.0,수지구,풍덕천동,여,36.0,30대이하,4977,매장C,NaN,10:05
2,2018-01-02,화,1,1,1506656256,정상회원,축산물,알,유정란,유정란/매장용(10알/국내산),1.0,수지구,풍덕천동,여,36.0,30대이하,7083,매장C,NaN,10:05
3,2018-01-02,화,1,1,1023108864,정상회원,반찬,두부/유부,두부,연두부(100g),1.0,수지구,풍덕천동,여,36.0,30대이하,766,매장C,NaN,10:08
4,2018-01-02,화,1,1,1476143616,정상회원,간식,빵,"식빵, 식사대용",아침빵(240g/8개)/매장,1.0,수지구,풍덕천동,여,34.0,30대이하,4403,매장C,NaN,10:09
5,2018-01-02,화,1,1,716128320,정상회원,축산물,알,유정란,유정란/매장용(10알/국내산),1.0,수지구,풍덕천동,여,51.0,50대,7083,매장C,NaN,10:10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
705564,2018-06-30,토,6,26,1278913920,정상회원,수산,해조,김,구운김밥김(10장),1.0,수지구,동천동,여,39.0,30대이하,3446,매장A,NaN,16:43
705565,2018-06-30,토,6,26,867143616,정상회원,간식,빵,"케이크,롤,선물",플레인롤케이크(90g/조각롤),-1.0,기타,기타,여,60.0,60대,-6126,매장A,20180630.0,15:54
705566,2018-06-30,토,6,26,146297344,정상회원,수산,건어물,멸치류,국물멸치(300g),1.0,수지구,성복동,여,51.0,50대,9189,매장A,NaN,17:56
705567,2018-06-30,토,6,26,1532985472,정상회원,수산,해조,미역/다시마,자른다시마(100g),1.0,수지구,동천동,여,63.0,60대,5169,매장A,NaN,14:37
705568,2018-06-30,토,6,26,1532985472,정상회원,반찬,두부/유부,두부,두부(1모:420g),2.0,수지구,동천동,여,63.0,60대,7466,매장A,NaN,14:37

In [58]:
df1.loc[~cond1] ## 위와 같이 40대를 제외한 데이터들만 불러옴

,공급일자,요일,공급월,공급주차,회원번호,조합원상태,물품대분류,물품중분류,물품소분류,물품명,구매수량,주소-구,주소-동,성별,연령,연령대,구매금액,구매매장,반품_원거래일자,구매시각
1,2018-01-02,화,1,1,1506656256,정상회원,채소,버섯,느타리버섯,느타리버섯(300g),1.0,수지구,풍덕천동,여,36.0,30대이하,4977,매장C,NaN,10:05
2,2018-01-02,화,1,1,1506656256,정상회원,축산물,알,유정란,유정란/매장용(10알/국내산),1.0,수지구,풍덕천동,여,36.0,30대이하,7083,매장C,NaN,10:05
3,2018-01-02,화,1,1,1023108864,정상회원,반찬,두부/유부,두부,연두부(100g),1.0,수지구,풍덕천동,여,36.0,30대이하,766,매장C,NaN,10:08
4,2018-01-02,화,1,1,1476143616,정상회원,간식,빵,"식빵, 식사대용",아침빵(240g/8개)/매장,1.0,수지구,풍덕천동,여,34.0,30대이하,4403,매장C,NaN,10:09
5,2018-01-02,화,1,1,716128320,정상회원,축산물,알,유정란,유정란/매장용(10알/국내산),1.0,수지구,풍덕천동,여,51.0,50대,7083,매장C,NaN,10:10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
705564,2018-06-30,토,6,26,1278913920,정상회원,수산,해조,김,구운김밥김(10장),1.0,수지구,동천동,여,39.0,30대이하,3446,매장A,NaN,16:43
705565,2018-06-30,토,6,26,867143616,정상회원,간식,빵,"케이크,롤,선물",플레인롤케이크(90g/조각롤),-1.0,기타,기타,여,60.0,60대,-6126,매장A,20180630.0,15:54
705566,2018-06-30,토,6,26,146297344,정상회원,수산,건어물,멸치류,국물멸치(300g),1.0,수지구,성복동,여,51.0,50대,9189,매장A,NaN,17:56
705567,2018-06-30,토,6,26,1532985472,정상회원,수산,해조,미역/다시마,자른다시마(100g),1.0,수지구,동천동,여,63.0,60대,5169,매장A,NaN,14:37
705568,2018-06-30,토,6,26,1532985472,정상회원,반찬,두부/유부,두부,두부(1모:420g),2.0,수지구,동천동,여,63.0,60대,7466,매장A,NaN,14:37

In [59]:
df1['성별'].value_counts()

여    662024
남     43542
Name: 성별, dtype: int64

In [60]:
cond1 = (df1['연령대'] == '40대')

In [62]:
cond2 = (df1['성별'] == '남')

In [63]:
df1.loc[cond1 & cond2] ## 성별이 남성이면서 연령대가 40대의 사람만 불러옴

,공급일자,요일,공급월,공급주차,회원번호,조합원상태,물품대분류,물품중분류,물품소분류,물품명,구매수량,주소-구,주소-동,성별,연령,연령대,구매금액,구매매장,반품_원거래일자,구매시각
34,2018-01-02,화,1,1,570500992,정상회원,간식,떡,즉석떡,절편(170g),1.0,수지구,풍덕천동,남,47.0,40대,3829,매장C,NaN,11:19
38,2018-01-02,화,1,1,1314239168,정상회원,간식,과자,스낵,밥풀과자(120g),4.0,수지구,성복동,남,48.0,40대,20676,매장C,NaN,11:22
196,2018-01-02,화,1,1,850970432,정상회원,채소,뿌리채소,당근,당근(1kg),1.0,기흥구,보정동,남,45.0,40대,4786,매장C,NaN,17:11
197,2018-01-02,화,1,1,850970432,정상회원,축산물,알,유정란,동물복지유정란(10알/국내산),1.0,기흥구,보정동,남,45.0,40대,6892,매장C,NaN,17:11
328,2018-01-02,화,1,1,1090633856,탈퇴,채소,잎/줄기채소,시금치,시금치(300g),1.0,수지구,신봉동,남,41.0,40대,4403,매장D,NaN,17:09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
705197,2018-06-30,토,6,26,273041728,정상회원,반찬,즉석조리,간편요리,잡채(300g),1.0,수지구,풍덕천동,남,44.0,40대,9668,매장C,NaN,13:53
705258,2018-06-30,토,6,26,163435648,정상회원,수산,수산가공,젓갈/액젓,새우육젓(250g),1.0,수지구,풍덕천동,남,49.0,40대,26802,매장C,NaN,17:20
705334,2018-06-30,토,6,26,408947328,정상회원,축산물,소,한우(냉장),한우채끝(안심대안/200g/신선육),1.0,기타,기타,남,46.0,40대,23739,매장D,NaN,12:31
705335,2018-06-30,토,6,26,408947328,정상회원,반찬,두부/유부,두부,두부(1모:420g),1.0,기타,기타,남,46.0,40대,3733,매장D,NaN,12:31
705542,2018-06-30,토,6,26,932214976,정상회원,간식,빵,"식빵, 식사대용",쌀로만든잉글리쉬머핀(66g×4개)/매장,1.0,기타,기타,남,41.0,40대,7466,매장A,NaN,11:36

In [65]:
df1.loc[cond1 | cond2]

,공급일자,요일,공급월,공급주차,회원번호,조합원상태,물품대분류,물품중분류,물품소분류,물품명,구매수량,주소-구,주소-동,성별,연령,연령대,구매금액,구매매장,반품_원거래일자,구매시각
0,2018-01-02,화,1,1,272369856,정상회원,과실,과일,사과,사과/유(1.5kg),1.0,수지구,풍덕천동,여,45.0,40대,22207,매장C,NaN,10:04
17,2018-01-02,화,1,1,1049686784,정상회원,간식,식사대용,식사대용/기타,닭고기볶음밥(300g),1.0,수지구,풍덕천동,여,40.0,40대,5743,매장C,NaN,10:31
18,2018-01-02,화,1,1,164510272,정상회원,채소,양념채소,양파,양파(2kg),1.0,수지구,풍덕천동,여,42.0,40대,8711,매장C,NaN,10:32
19,2018-01-02,화,1,1,1185171072,정상회원,양념/가루,가루,양념가루,카레(순한맛:100g),1.0,수지구,풍덕천동,여,47.0,40대,5169,매장C,NaN,10:37
20,2018-01-02,화,1,1,1206815744,정상회원,채소,양념채소,대파,대파(700g),1.0,수지구,풍덕천동,여,42.0,40대,5265,매장C,NaN,10:39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
705556,2018-06-30,토,6,26,572193664,정상회원,반찬,두부/유부,콩가공/기타,콩국물(300g),1.0,수지구,풍덕천동,여,46.0,40대,2202,매장A,NaN,13:48
705560,2018-06-30,토,6,26,1333795840,정상회원,반찬,밑반찬,김가공,김부각(50g),1.0,수지구,풍덕천동,여,41.0,40대,7275,매장A,NaN,15:28
705561,2018-06-30,토,6,26,1333795840,정상회원,채소,잎/줄기채소,브로컬리,브로컬리(250g),1.0,수지구,풍덕천동,여,41.0,40대,3982,매장A,NaN,15:28
705569,2018-06-30,토,6,26,1209779776,정상회원,간식,과자,스낵,하늘바다새우(60g),1.0,수지구,동천동,여,41.0,40대,3542,매장A,NaN,18:04
705570,2018-06-30,토,6,26,301961920,정상회원,음료,음료,빙과,포도꽁꽁(120ml)/매장용,1.0,수지구,풍덕천동,여,49.0,40대,1914,매장A,NaN,16:36

In [66]:
# 30대 여성 추출 > 구매금액 높은순서로 정렬

In [67]:
# 하나의 파일로 저장

In [68]:
cond1 = (df1['연령대'] == '30대이하')
cond2 = (df1['성별'] == '여')

In [73]:
df3 = df1[cond1 & cond2].sort_values(by='구매금액', ascending=False)

In [72]:
df3.shape

(94886, 20)

In [74]:
df3

,공급일자,요일,공급월,공급주차,회원번호,조합원상태,물품대분류,물품중분류,물품소분류,물품명,구매수량,주소-구,주소-동,성별,연령,연령대,구매금액,구매매장,반품_원거래일자,구매시각
155255,2018-02-09,금,2,6,236805184,정상회원,건강,건강일반,건강/기타,홍삼/도라지절편모음(각 20g*5개),17.0,수지구,상현동,여,39.0,30대이하,1448255,매장B,NaN,12:17
154682,2018-02-09,금,2,6,236805184,정상회원,건강,홍삼/녹용,녹용,꽃사슴녹용액(남성/30봉*90ml),5.0,수지구,상현동,여,39.0,30대이하,631757,매장B,NaN,12:17
154683,2018-02-09,금,2,6,236805184,정상회원,수산,냉동수산,냉동생선,갈치선물모음(3마리),2.0,수지구,상현동,여,39.0,30대이하,604955,매장B,NaN,12:17
124021,2018-02-01,목,2,5,796003136,정상회원,건강,건강일반,추출/농축액,흑염소진액(100ml*30봉),3.0,수지구,동천동,여,39.0,30대이하,499662,매장A,NaN,15:51
682834,2018-06-25,월,6,26,678182400,정상회원,건강,건강일반,추출/농축액,흑염소진액(100ml*30봉),3.0,분당구,수내동,여,33.0,30대이하,499662,매장A,NaN,11:12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
638874,2018-06-15,금,6,24,1023108864,정상회원,건강,홍삼/녹용,홍삼,홍삼액(6년근/30봉),-1.0,수지구,풍덕천동,여,36.0,30대이하,-118694,매장C,20180611.0,10:28
357637,2018-04-02,월,4,14,678182400,정상회원,건강,홍삼/녹용,녹용,꽃사슴녹용액(수험생/30봉*90ml),-1.0,분당구,수내동,여,33.0,30대이하,-126351,매장C,20180402.0,16:27
330306,2018-03-26,월,3,13,584736512,정상회원,생활용품,식기/편백,무쇠,무쇠미니팬,-1.0,수지구,풍덕천동,여,39.0,30대이하,-127309,매장A,NaN,17:14
482357,2018-05-04,금,5,18,1438455680,정상회원,수산,생물수산,패류/갑각류,붉은대게(550g*3미),-1.0,수지구,상현동,여,37.0,30대이하,-127691,매장A,20180504.0,16:32
209220,2018-02-23,금,2,8,1122725952,정상회원,건강,홍삼/녹용,홍삼,주머니속홍삼정(10ml*10봉*3박스),-1.0,수지구,신봉동,여,37.0,30대이하,-166554,매장D,20180223.0,16:43

In [76]:
df3.to_csv('result.csv', encoding='cp949')